# Generated by Django 4.2 on 2026-04-01 23:34

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ResumeSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('ingesting', 'Ingesting'), ('generating', 'Generating'), ('review', 'Review'), ('exporting', 'Exporting'), ('complete', 'Complete'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('source_pdf_path', models.TextField()),
                ('output_pdf_path', models.TextField(blank=True, default='')),
                ('output_artifact_type', models.CharField(choices=[('single_pdf', 'Single PDF'), ('dual_pdf', 'Dual PDF')], default='single_pdf', max_length=20)),
                ('generation_mode', models.CharField(choices=[('resume_only', 'Resume only'), ('resume_and_cover_letter', 'Resume and cover letter')], default='resume_only', max_length=30)),
                ('credential_mode', models.CharField(choices=[('app_key', 'App key'), ('user_key', 'User key')], default='app_key', max_length=10)),
                ('selected_model', models.CharField(default='gpt-5.1', max_length=100)),
                ('job_description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GenerationRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('model_name', models.CharField(max_length=100)),
                ('credential_mode', models.CharField(choices=[('app_key', 'App key'), ('user_key', 'User key')], max_length=10)),
                ('prompt_version', models.CharField(max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('succeeded', 'Succeeded'), ('failed', 'Failed'), ('timed_out', 'Timed out')], default='pending', max_length=20)),
                ('error_code', models.CharField(blank=True, choices=[('timeout_user_key', 'Timeout (user key)'), ('timeout_app_key', 'Timeout (app key)'), ('unsupported_pdf', 'Unsupported PDF'), ('structured_output_invalid', 'Structured output invalid'), ('model_unavailable', 'Model unavailable')], default='', max_length=40)),
                ('error_summary', models.TextField(blank=True, default='')),
                ('started_at', models.DateTimeField()),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('duration_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generation_runs', to='resume_sessions.resumesession')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='CoverLetterDraft',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('original_grounding_summary', models.TextField()),
                ('tailored_content', models.TextField()),
                ('user_edited_content', models.TextField(blank=True, default='')),
                ('review_status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved')], default='pending', max_length=10)),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cover_letter_draft', to='resume_sessions.resumesession')),
            ],
        ),
        migrations.CreateModel(
            name='ResumeSection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('section_key', models.CharField(max_length=100)),
                ('order_index', models.PositiveIntegerField()),
                ('page_number', models.PositiveIntegerField()),
                ('bbox_x0', models.FloatField()),
                ('bbox_y0', models.FloatField()),
                ('bbox_x1', models.FloatField()),
                ('bbox_y1', models.FloatField()),
                ('original_content', models.TextField()),
                ('tailored_content', models.TextField(blank=True, default='')),
                ('user_edited_content', models.TextField(blank=True, default='')),
                ('review_status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='resume_sessions.resumesession')),
            ],
            options={
                'ordering': ['order_index'],
                'unique_together': {('session', 'order_index'), ('session', 'section_key')},
            },
        ),
    ]
